# Generated by Django 6.0.5 on 2026-05-31 16:29

import django.db.models.constraints
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('photos', '0002_alter_photo_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                (
                    'description',
                    models.TextField(
                        blank=True, default='', verbose_name='description'
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('draft', 'Draft'), ('published', 'Published')],
                        default='draft',
                        max_length=20,
                        verbose_name='status',
                    ),
                ),
                (
                    'published_at',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='published at'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='created at'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='updated at'),
                ),
            ],
            options={
                'verbose_name': 'album',
                'verbose_name_plural': 'albums',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlbumPhoto',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('position', models.PositiveIntegerField(verbose_name='position')),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='created at'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='updated at'),
                ),
                (
                    'album',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='photo_links',
                        to='albums.album',
                        verbose_name='album',
                    ),
                ),
                (
                    'photo',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='album_links',
                        to='photos.photo',
                        verbose_name='photo',
                    ),
                ),
            ],
            options={
                'verbose_name': 'album photo',
                'verbose_name_plural': 'album photos',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='album',
            name='photos',
            field=models.ManyToManyField(
                related_name='albums',
                through='albums.AlbumPhoto',
                to='photos.photo',
                verbose_name='photos',
            ),
        ),
        migrations.AddConstraint(
            model_name='albumphoto',
            constraint=models.UniqueConstraint(
                fields=('photo', 'album'), name='unique_photo_album'
            ),
        ),
        migrations.AddConstraint(
            model_name='albumphoto',
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable['DEFERRED'],
                fields=('album', 'position'),
                name='unique_album_position',
            ),
        ),
    ]
