# Generated by Django 6.0.5 on 2026-05-28 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'album',
                'verbose_name_plural': 'albums',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlbumPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='position')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_links', to='albums.album', verbose_name='album')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_links', to='photos.photo', verbose_name='photo')),
            ],
            options={
                'verbose_name': 'album photo',
                'verbose_name_plural': 'album photos',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='album',
            name='photos',
            field=models.ManyToManyField(related_name='albums', through='albums.AlbumPhoto', to='photos.photo', verbose_name='photos'),
        ),
        migrations.AddIndex(
            model_name='albumphoto',
            index=models.Index(fields=['album', 'position'], name='albums_albu_album_i_8a964a_idx'),
        ),
        migrations.AddConstraint(
            model_name='albumphoto',
            constraint=models.UniqueConstraint(fields=('photo', 'album'), name='unique_photo_album'),
        ),
        migrations.AddConstraint(
            model_name='albumphoto',
            constraint=models.UniqueConstraint(fields=('album', 'position'), name='unique_album_position'),
        ),
    ]
