# Generated by Django 6.0.5 on 2026-05-28 22:26

import django.db.models.constraints
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('albums', '0001_initial'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='albumphoto',
            name='unique_album_position',
        ),
        migrations.RemoveIndex(
            model_name='albumphoto',
            name='albums_albu_album_i_8a964a_idx',
        ),
        migrations.AlterField(
            model_name='albumphoto',
            name='album',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='photo_links',
                to='albums.album',
                verbose_name='album',
            ),
        ),
        migrations.AddConstraint(
            model_name='albumphoto',
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable['DEFERRED'],
                fields=('album', 'position'),
                name='unique_album_position',
            ),
        ),
    ]
