# Generated by Django 6.0.5 on 2026-05-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='published_at',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='published at'
            ),
        ),
        migrations.AddField(
            model_name='album',
            name='status',
            field=models.CharField(
                choices=[('draft', 'Draft'), ('published', 'Published')],
                default='draft',
                max_length=20,
                verbose_name='status',
            ),
        ),
    ]
