# Generated by Django 6.0.6 on 2026-06-08 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('photos', '0002_alter_photo_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoExif',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'camera_make',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=255,
                        verbose_name='camera make',
                    ),
                ),
                (
                    'camera_model',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=255,
                        verbose_name='camera model',
                    ),
                ),
                (
                    'lens',
                    models.CharField(
                        blank=True, default='', max_length=255, verbose_name='lens'
                    ),
                ),
                (
                    'aperture',
                    models.FloatField(blank=True, null=True, verbose_name='aperture'),
                ),
                (
                    'exposure_time',
                    models.FloatField(
                        blank=True, null=True, verbose_name='exposure time'
                    ),
                ),
                (
                    'focal_length',
                    models.FloatField(
                        blank=True, null=True, verbose_name='focal length'
                    ),
                ),
                (
                    'iso',
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name='ISO'
                    ),
                ),
                (
                    'latitude',
                    models.FloatField(blank=True, null=True, verbose_name='latitude'),
                ),
                (
                    'longitude',
                    models.FloatField(blank=True, null=True, verbose_name='longitude'),
                ),
                ('raw', models.JSONField(default=dict, verbose_name='raw')),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='created at'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='updated at'),
                ),
                (
                    'photo',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='exif',
                        to='photos.photo',
                        verbose_name='photo',
                    ),
                ),
            ],
            options={
                'verbose_name': 'EXIF',
                'verbose_name_plural': 'EXIF',
            },
        ),
    ]
