# Generated by Django 6.0.5 on 2026-05-26 19:38

import curio.photos.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                (
                    'file',
                    models.FileField(
                        upload_to=curio.photos.models._photo_upload, verbose_name='file'
                    ),
                ),
                (
                    'media_type',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=100,
                        verbose_name='media type',
                    ),
                ),
                (
                    'file_size',
                    models.PositiveIntegerField(default=0, verbose_name='file size'),
                ),
                (
                    'description',
                    models.TextField(
                        blank=True, default='', verbose_name='description'
                    ),
                ),
                (
                    'produced_at',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='produced at'
                    ),
                ),
                (
                    'width',
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name='width'
                    ),
                ),
                (
                    'height',
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name='height'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='created at'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='updated at'),
                ),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
            },
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('exif', 'EXIF'),
                            ('dc', 'Dublin Core'),
                            ('custom', 'Custom'),
                        ],
                        max_length=16,
                        verbose_name='type',
                    ),
                ),
                ('data', models.JSONField(verbose_name='data')),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='created at'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='updated at'),
                ),
                (
                    'photo',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='metadata',
                        to='photos.photo',
                        verbose_name='photo',
                    ),
                ),
            ],
            options={
                'verbose_name': 'metadata',
                'verbose_name_plural': 'metadata',
            },
        ),
    ]
