# Generated by Django 6.0.5 on 2026-05-17 12:25

import curio.resources.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Document')], max_length=16, verbose_name='type')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('produced_at', models.DateTimeField(blank=True, null=True, verbose_name='produced at')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='poster')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'resource',
                'verbose_name_plural': 'resources',
            },
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('exif', 'EXIF'), ('dc', 'Dublin Core'), ('custom', 'Custom')], max_length=16, verbose_name='type')),
                ('data', models.JSONField(verbose_name='data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='resources.resource', verbose_name='resource')),
            ],
            options={
                'verbose_name': 'metadata',
                'verbose_name_plural': 'metadata',
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=curio.resources.models._media_file_upload, verbose_name='file')),
                ('media_type', models.CharField(blank=True, default='', max_length=100, verbose_name='media type')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='file size')),
                ('role', models.CharField(blank=True, default='', max_length=50, verbose_name='role')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='duration')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='width')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='height')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='page count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='resources.resource', verbose_name='resource')),
            ],
            options={
                'verbose_name': 'media file',
                'verbose_name_plural': 'media files',
                'ordering': ['order'],
            },
        ),
    ]
