# Generated by Django 6.0.5 on 2026-05-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='media_type',
            field=models.CharField(
                blank=True, default='', max_length=100, verbose_name='media type'
            ),
        ),
    ]
