# Generated by Django 6.0.5 on 2026-05-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resource_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='page count'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Document')], max_length=16, verbose_name='type'),
        ),
    ]
