# Generated by Django 6.0.5 on 2026-05-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('resources', '0003_resource_page_count_alter_resource_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
    ]
